version: '3'

services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '4000:80'
  postgres:
    image: 'postgres:9.6.11-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:5.0.3-alpine'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
